# Generated by Django 3.2.9 on 2021-11-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_url', models.CharField(max_length=550)),
                ('meme_value', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
    ]
